### ISSUE TITLE
User#profileBannerUrl is nullable

### ISSUE THREAD

**Issue by pois0** [NephyProject/Penicillin#10]
When they haven't set their background, it'll be null.
User#profileBackgroundImageUrlHttps is same as it.

**Comment by SlashNephy** [comment]
`CommonUser` 内の `profileBackgroundImageUrl`, `profileBackgroundImageUrlHttps` を `String?` に変更します。

**Comment by pois0** [comment]
アホだったのですがこれは全てウソで正しくはUser#profileBannerUrlです

**Comment by SlashNephy** [comment]
Banner は未設定だと null になるけど
`profileBackgroundImageUrl` だと未設定のユーザは デフォルト画像がセットされてるとかそういうことですか？
